name: Build Windows 7 EXE
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      # Bundle images in the same folder as the script:
      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --add-data "*.ico;." --add-data "*.png;." "18F-FAMILY APP.py"

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: 18F-FAMILY APP.exe
          path: dist/18F-FAMILY APP.exe
