name: Build Windows 7 EXE
on: [push]
jobs:
  build:
    runs-on: windows-2019  # Uses Windows Server 2019 (Python 3.8 compatible)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile 18FFAMILY.py

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: 18FFAMILY.exe
          path: dist/18FFAMILY.exe
